-- ============================================================
-- 全アプリテーブルで Row Level Security (RLS) を有効化
-- ============================================================
-- 目的:
-- - Supabase の anon / authenticated が PostgREST 経由でテーブルに触れないようにする
-- - ポリシー未作成のため、上記ロールは行へのアクセス不可（デフォルト拒否）
-- - Prisma は service_role で接続する想定のため RLS をバイパスし、既存動作は維持される
-- 参照: 技術的負債 D1（RLS 未設定リスク）の解消
-- ============================================================

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Watchlist" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ChartDrawing" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Trade" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TradeNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AISummary" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MarketSnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MatchResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderPreset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EvaluationLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DataPreset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OHLCVCandle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TradeNoteRaw" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RevaluationJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BacktestRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BacktestResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BacktestEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MatchDetail" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Strategy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyBacktestRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyBacktestResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyBacktestEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyAlert" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyAlertLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WalkForwardRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WalkForwardSplit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MonteCarloRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationBatchConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationSkipLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MarketResearch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AITradePlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VirtualTrade" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VirtualPortfolio" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AITradeNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AINoteSummary" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CTraderToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TickData" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RealtimeOHLCV" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyComparisonSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyComparisonResult" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StrategyCorrelation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PortfolioOptimization" ENABLE ROW LEVEL SECURITY;
